"""
Production database migration contracts for ETIS Engineering Studio.

Application startup must not be the mechanism that creates or upgrades the
production schema. Alembic owns versioned production schema evolution.
"""

from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

from apps.api.app.models import Base


ROOT = Path(__file__).resolve().parents[1]
ALEMBIC_INI = ROOT / "alembic.ini"


def test_alembic_head_builds_complete_schema_from_empty_database(tmp_path):
    """
    An empty database upgraded to Alembic head must contain exactly the
    application tables represented by current SQLAlchemy metadata.

    This makes the initial migration a complete reproducible production
    baseline rather than a partial migration layered on top of create_all().
    """
    assert ALEMBIC_INI.is_file(), (
        "alembic.ini is required for versioned production schema management"
    )

    database_path = tmp_path / "migration-contract.db"
    database_url = f"sqlite:///{database_path}"

    config = Config(str(ALEMBIC_INI))
    config.set_main_option("sqlalchemy.url", database_url)

    command.upgrade(config, "head")

    engine = create_engine(database_url)
    try:
        migrated_tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    migrated_tables.discard("alembic_version")
    model_tables = set(Base.metadata.tables.keys())

    assert migrated_tables == model_tables, (
        "Alembic head and SQLAlchemy model metadata disagree.\n"
        f"Missing from migration: {sorted(model_tables - migrated_tables)}\n"
        f"Unexpected in migration: {sorted(migrated_tables - model_tables)}"
    )


def test_production_init_db_never_creates_schema(monkeypatch):
    """
    Production application startup must never create or mutate database schema.

    Production schema ownership belongs to Alembic migrations. Development
    and test environments may retain create_all()-based convenience behavior.
    """
    import apps.api.app.db as db_module

    class ProductionSettings:
        etis_env = "production"

    def forbidden_create_all(*args, **kwargs):
        raise AssertionError(
            "Base.metadata.create_all() must never run during production startup"
        )

    monkeypatch.setattr(db_module, "settings", ProductionSettings())
    monkeypatch.setattr(
        db_module.Base.metadata,
        "create_all",
        forbidden_create_all,
    )

    db_module.init_db()


def test_alembic_baseline_round_trips_cleanly(tmp_path):
    """
    The baseline migration must support a complete upgrade -> downgrade cycle.

    After downgrade to base, no application tables or Alembic version table
    should remain.
    """
    database_path = tmp_path / "migration-roundtrip.db"
    database_url = f"sqlite:///{database_path}"

    config = Config(str(ALEMBIC_INI))
    config.set_main_option("sqlalchemy.url", database_url)

    command.upgrade(config, "head")
    command.downgrade(config, "base")

    engine = create_engine(database_url)
    try:
        remaining_tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    application_tables = remaining_tables - {"alembic_version"}

    assert application_tables == set(), (
        "Downgrade to base left application tables behind: "
        f"{sorted(application_tables)}"
    )

    # Alembic may retain its bookkeeping table at base, but it must contain
    # no current revision.
    from sqlalchemy import text

    engine = create_engine(database_url)
    try:
        with engine.connect() as connection:
            current_versions = connection.execute(
                text("SELECT version_num FROM alembic_version")
            ).fetchall()
    finally:
        engine.dispose()

    assert current_versions == [], (
        "Downgrade to base must leave no active Alembic revision"
    )


def test_alembic_head_has_no_model_drift(tmp_path):
    """
    Once upgraded to head, Alembic autogeneration must see no schema changes.

    This prevents the checked-in migration history from silently drifting away
    from the SQLAlchemy model metadata.
    """
    database_path = tmp_path / "migration-drift.db"
    database_url = f"sqlite:///{database_path}"

    config = Config(str(ALEMBIC_INI))
    config.set_main_option("sqlalchemy.url", database_url)

    command.upgrade(config, "head")

    # Alembic raises AutogenerateDiffsDetected when metadata and the migrated
    # schema disagree.
    command.check(config)


def test_postgresql_alembic_head_matches_model_metadata():
    """
    Validate the production migration history against a real PostgreSQL
    database when ETIS_TEST_POSTGRES_URL is supplied by CI.

    Local development does not require a PostgreSQL installation; CI owns the
    production-dialect migration proof.
    """
    import os

    import pytest

    database_url = os.getenv("ETIS_TEST_POSTGRES_URL", "").strip()
    if not database_url:
        if os.getenv("CI") or os.getenv("GITHUB_ACTIONS"):
            pytest.fail(
                "CI must provide ETIS_TEST_POSTGRES_URL so production "
                "migrations are validated against PostgreSQL"
            )

        pytest.skip("ETIS_TEST_POSTGRES_URL is not configured")

    config = Config(str(ALEMBIC_INI))
    config.set_main_option("sqlalchemy.url", database_url)

    # The CI database is dedicated to this test. Always normalize it to base
    # before applying the current production migration head.
    command.downgrade(config, "base")
    command.upgrade(config, "head")

    engine = create_engine(database_url)
    try:
        migrated_tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    migrated_tables.discard("alembic_version")
    model_tables = set(Base.metadata.tables.keys())

    assert migrated_tables == model_tables, (
        "PostgreSQL Alembic head and SQLAlchemy metadata disagree.\n"
        f"Missing from migration: {sorted(model_tables - migrated_tables)}\n"
        f"Unexpected in migration: {sorted(migrated_tables - model_tables)}"
    )

    # Autogeneration must detect no PostgreSQL-specific schema drift.
    command.check(config)
