"""baseline production schema

Revision ID: fcd1f7578040
Revises:
Create Date: 2026-08-17 08:59:18.046252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd1f7578040'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=40), nullable=False),
    sa.Column('namespace', sa.String(length=60), nullable=False),
    sa.Column('term_label', sa.String(length=100), nullable=False),
    sa.Column('starts_on', sa.String(length=20), nullable=False),
    sa.Column('ends_on', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_terms_course_code'), 'course_terms', ['course_code'], unique=False)
    op.create_index(op.f('ix_course_terms_namespace'), 'course_terms', ['namespace'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_namespace', sa.String(length=50), nullable=False),
    sa.Column('team_key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('repo_full_name', sa.String(length=250), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('current_phase', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_namespace', 'team_key')
    )
    op.create_index(op.f('ix_teams_course_namespace'), 'teams', ['course_namespace'], unique=False)
    op.create_index(op.f('ix_teams_team_key'), 'teams', ['team_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_login'), 'users', ['github_login'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('login', sa.String(length=240), nullable=False),
    sa.Column('requires_course_authorization', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('meeting_pattern', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['course_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'section_key')
    )
    op.create_index(op.f('ix_course_sections_section_key'), 'course_sections', ['section_key'], unique=False)
    op.create_index(op.f('ix_course_sections_term_id'), 'course_sections', ['term_id'], unique=False)
    op.create_table('evidence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('commit_sha', sa.String(length=80), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_snapshots_phase_id'), 'evidence_snapshots', ['phase_id'], unique=False)
    op.create_index(op.f('ix_evidence_snapshots_team_id'), 'evidence_snapshots', ['team_id'], unique=False)
    op.create_table('github_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=120), nullable=False),
    sa.Column('github_user_id', sa.String(length=80), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_identities_github_login'), 'github_identities', ['github_login'], unique=True)
    op.create_index(op.f('ix_github_identities_user_id'), 'github_identities', ['user_id'], unique=True)
    op.create_table('institutional_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=120), nullable=False),
    sa.Column('institutional_email', sa.String(length=240), nullable=False),
    sa.Column('identity_provider', sa.String(length=40), nullable=False),
    sa.Column('provider_subject', sa.String(length=240), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_identities_institutional_email'), 'institutional_identities', ['institutional_email'], unique=True)
    op.create_index(op.f('ix_institutional_identities_provider_subject'), 'institutional_identities', ['provider_subject'], unique=False)
    op.create_index(op.f('ix_institutional_identities_student_id'), 'institutional_identities', ['student_id'], unique=True)
    op.create_index(op.f('ix_institutional_identities_user_id'), 'institutional_identities', ['user_id'], unique=True)
    op.create_table('instructor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.String(length=10), nullable=False),
    sa.Column('provenance', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_notes_team_id'), 'instructor_notes', ['team_id'], unique=False)
    op.create_table('repository_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=260), nullable=False),
    sa.Column('clone_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('github_app_installed', sa.Boolean(), nullable=False),
    sa.Column('installation_id', sa.String(length=100), nullable=False),
    sa.Column('connected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_connections_repo_full_name'), 'repository_connections', ['repo_full_name'], unique=False)
    op.create_index(op.f('ix_repository_connections_team_id'), 'repository_connections', ['team_id'], unique=True)
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scenario_id', sa.String(length=120), nullable=False),
    sa.Column('challenge_state_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_sessions_phase_id'), 'review_sessions', ['phase_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_team_id'), 'review_sessions', ['team_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_user_id'), 'review_sessions', ['user_id'], unique=False)
    op.create_table('team_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('responsibility_role', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id')
    )
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_user_id'), 'team_memberships', ['user_id'], unique=False)
    op.create_table('ai_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_namespace', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('response_id', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_microusd', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_events_course_namespace'), 'ai_usage_events', ['course_namespace'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_phase_id'), 'ai_usage_events', ['phase_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_purpose'), 'ai_usage_events', ['purpose'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_session_id'), 'ai_usage_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_team_id'), 'ai_usage_events', ['team_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_user_id'), 'ai_usage_events', ['user_id'], unique=False)
    op.create_table('membership_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_events_section_id'), 'membership_events', ['section_id'], unique=False)
    op.create_index(op.f('ix_membership_events_user_id'), 'membership_events', ['user_id'], unique=False)
    op.create_table('phase_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.String(length=10), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accept_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_override', sa.String(length=20), nullable=False),
    sa.Column('instructor_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'phase_id')
    )
    op.create_index(op.f('ix_phase_schedules_phase_id'), 'phase_schedules', ['phase_id'], unique=False)
    op.create_index(op.f('ix_phase_schedules_section_id'), 'phase_schedules', ['section_id'], unique=False)
    op.create_table('review_finding_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('evidence_path', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'finding_id')
    )
    op.create_index(op.f('ix_review_finding_states_finding_id'), 'review_finding_states', ['finding_id'], unique=False)
    op.create_index(op.f('ix_review_finding_states_snapshot_id'), 'review_finding_states', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_review_finding_states_status'), 'review_finding_states', ['status'], unique=False)
    op.create_index(op.f('ix_review_finding_states_team_id'), 'review_finding_states', ['team_id'], unique=False)
    op.create_table('review_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('lens', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_refs_json', sa.Text(), nullable=False),
    sa.Column('signals_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_turns_session_id'), 'review_turns', ['session_id'], unique=False)
    op.create_table('section_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'user_id')
    )
    op.create_index(op.f('ix_section_enrollments_section_id'), 'section_enrollments', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_enrollments_status'), 'section_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_section_enrollments_user_id'), 'section_enrollments', ['user_id'], unique=False)
    op.create_table('section_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'user_id', 'staff_role')
    )
    op.create_index(op.f('ix_section_staff_section_id'), 'section_staff', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_staff_user_id'), 'section_staff', ['user_id'], unique=False)
    op.create_table('team_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_sections_section_id'), 'team_sections', ['section_id'], unique=False)
    op.create_index(op.f('ix_team_sections_team_id'), 'team_sections', ['team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_sections_team_id'), table_name='team_sections')
    op.drop_index(op.f('ix_team_sections_section_id'), table_name='team_sections')
    op.drop_table('team_sections')
    op.drop_index(op.f('ix_section_staff_user_id'), table_name='section_staff')
    op.drop_index(op.f('ix_section_staff_section_id'), table_name='section_staff')
    op.drop_table('section_staff')
    op.drop_index(op.f('ix_section_enrollments_user_id'), table_name='section_enrollments')
    op.drop_index(op.f('ix_section_enrollments_status'), table_name='section_enrollments')
    op.drop_index(op.f('ix_section_enrollments_section_id'), table_name='section_enrollments')
    op.drop_table('section_enrollments')
    op.drop_index(op.f('ix_review_turns_session_id'), table_name='review_turns')
    op.drop_table('review_turns')
    op.drop_index(op.f('ix_review_finding_states_team_id'), table_name='review_finding_states')
    op.drop_index(op.f('ix_review_finding_states_status'), table_name='review_finding_states')
    op.drop_index(op.f('ix_review_finding_states_snapshot_id'), table_name='review_finding_states')
    op.drop_index(op.f('ix_review_finding_states_finding_id'), table_name='review_finding_states')
    op.drop_table('review_finding_states')
    op.drop_index(op.f('ix_phase_schedules_section_id'), table_name='phase_schedules')
    op.drop_index(op.f('ix_phase_schedules_phase_id'), table_name='phase_schedules')
    op.drop_table('phase_schedules')
    op.drop_index(op.f('ix_membership_events_user_id'), table_name='membership_events')
    op.drop_index(op.f('ix_membership_events_section_id'), table_name='membership_events')
    op.drop_table('membership_events')
    op.drop_index(op.f('ix_ai_usage_events_user_id'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_team_id'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_session_id'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_purpose'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_phase_id'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_course_namespace'), table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    op.drop_index(op.f('ix_team_memberships_user_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_review_sessions_user_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_team_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_phase_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_index(op.f('ix_repository_connections_team_id'), table_name='repository_connections')
    op.drop_index(op.f('ix_repository_connections_repo_full_name'), table_name='repository_connections')
    op.drop_table('repository_connections')
    op.drop_index(op.f('ix_instructor_notes_team_id'), table_name='instructor_notes')
    op.drop_table('instructor_notes')
    op.drop_index(op.f('ix_institutional_identities_user_id'), table_name='institutional_identities')
    op.drop_index(op.f('ix_institutional_identities_student_id'), table_name='institutional_identities')
    op.drop_index(op.f('ix_institutional_identities_provider_subject'), table_name='institutional_identities')
    op.drop_index(op.f('ix_institutional_identities_institutional_email'), table_name='institutional_identities')
    op.drop_table('institutional_identities')
    op.drop_index(op.f('ix_github_identities_user_id'), table_name='github_identities')
    op.drop_index(op.f('ix_github_identities_github_login'), table_name='github_identities')
    op.drop_table('github_identities')
    op.drop_index(op.f('ix_evidence_snapshots_team_id'), table_name='evidence_snapshots')
    op.drop_index(op.f('ix_evidence_snapshots_phase_id'), table_name='evidence_snapshots')
    op.drop_table('evidence_snapshots')
    op.drop_index(op.f('ix_course_sections_term_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_section_key'), table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_github_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_team_key'), table_name='teams')
    op.drop_index(op.f('ix_teams_course_namespace'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_course_terms_namespace'), table_name='course_terms')
    op.drop_index(op.f('ix_course_terms_course_code'), table_name='course_terms')
    op.drop_table('course_terms')
    # ### end Alembic commands ###
